### ISSUE TITLE
pip install fails due to permissions

### ISSUE THREAD

**Issue by scottdangelo** [stevemart/nlc-icd10-demo#6]
on Mac, might need: 

sudo pip install -r requirements.txt --ignore-installed six

**Comment by stevemart** [comment]
going to close this for now as I modified the instructions to recommend the user create a virualenv, see step 3 of running the app locally:

```
3. (Optionally) create a virtual environment: virtualenv my-nlc-demo
  3a. Activate the virtual environment: ./my-nlc-demo/bin/activate
4. Run pip install -r requirements.txt to install the app's dependencies
```

I still sometimes use `sudo` when installing pip packages but it's not [recommended](https://stackoverflow.com/questions/15028648/is-it-acceptable-and-safe-to-run-pip-install-under-sudo) and i don't feel right in suggesting others do it
